# Generated by Django 5.2.13 on 2026-05-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_booking_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
