# Generated by Django 5.2.13 on 2026-04-25 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_companyprofile_availability_free_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Event Type Group',
                'verbose_name_plural': 'Event Type Groups',
            },
        ),
        migrations.AddField(
            model_name='eventtype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='booking.eventtypegroup', verbose_name='Group'),
        ),
    ]
