# Generated by Django 5.2.13 on 2026-04-28 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_eventtypegroup_eventtype_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtypegroup',
            options={'verbose_name': 'Agrupación de servicios', 'verbose_name_plural': 'Agrupaciones de servicios'},
        ),
        migrations.AddField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(blank=True, null=True, verbose_name='Special requests'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='privacy_policy_url',
            field=models.URLField(blank=True, null=True, verbose_name='Privacy policy URL'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='booking.eventtypegroup', verbose_name='Agrupación'),
        ),
    ]
