# Generated by Django 5.2.13 on 2026-04-29 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_companyprofile_booking_cooldown_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtypegroup',
            options={'verbose_name': 'Event Type Group', 'verbose_name_plural': 'Event Type Groups'},
        ),
        migrations.AddField(
            model_name='booking',
            name='google_sync_error',
            field=models.TextField(blank=True, null=True, verbose_name='Google sync error'),
        ),
        migrations.AddField(
            model_name='booking',
            name='google_sync_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('DISABLED', 'Disabled')], default='PENDING', max_length=20, verbose_name='Google sync status'),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last synced at'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_types', to='booking.eventtypegroup', verbose_name='Group'),
        ),
    ]
